### PR TITLE
Update Config.php

### PR DESCRIPTION
**Pull request by RanaMuhammadIrshad**

### CODE REVIEW

**Comment by amenk** [comment]
@RanaMuhammadIrshad  good catch I think
@DanieliMi  MR makes sense, correct?

**Comment by sprankhub** [comment]
While we are at it... Wouldn't this also need to be updated?

https://github.com/iMi-digital/magento2-friendly-captcha/blob/97aa259765c9c24a8402e258b08cd63a4ad7457e/Model/Config.php#L139

I guess this needs to be `https://api.friendlycaptcha.com/api/v1/puzzle`.

**Comment by amenk** [comment]
> While we are at it... Wouldn't this also need to be updated?
> 
> https://github.com/iMi-digital/magento2-friendly-captcha/blob/97aa259765c9c24a8402e258b08cd63a4ad7457e/Model/Config.php#L139
> 
> I guess this needs to be `https://api.friendlycaptcha.com/api/v1/puzzle`.

I think the standard is hard coded in the JS, if it is not supplied, that URL is used - but we could as well specify it

**Comment by sprankhub** [comment]
Okay. @amenk @DanieliMi, could we merge this very soon? Currently, the EU endpoint is broken with this module due to this bug.

**Comment by amenk** [comment]
@RanaMuhammadIrshad thank you for your contribution.
@sprankhub Thank you for the reminder. Merged & Released.

**Pull request merged**
